config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users

  get 'students/one' => 'students#one'
  get 'students/two' => 'students#two'
  get 'students/three' => 'students#three'
  get 'students/four' => 'students#four'




  resources :students do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  root 'students#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :student
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :student
  belongs_to :user
  validates_uniqueness_of :student_id, scope: :user_id
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    
    has_many :students, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :liked_students, through: :likes, source: :student
    has_many :comments, dependent: :destroy
    def already_liked?(student)
        self.likes.exists?(student_id: student.id)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      student = Student.find(params[:student_id])
      comment = student.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) #直前のページにリダイレクト
      end
    end
    private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(student_id: params[:student_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(student_id: params[:student_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
   
    before_action :authenticate_user!, only: [:new, :create]

    def index

        if params[:search] == nil
            @students= Student.all
        elsif params[:search] == ''
            @students= Student.all
        else
            @students = Student.where("title LIKE ? ",'%' + params[:search] + '%')
        end


       
        @students = @students.page(params[:page]).per(3)
    end


    def new
        @student = Student.new
    end
    
    def create
        student = Student.new(student_params)

        student.user_id = current_user.id 

        if student.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end

    def show
        @student = Student.find(params[:id])
        @comments = @student.comments
        @comment = Comment.new
    end

    def edit
        @student = Student.find(params[:id])
    end
    
    def update
        student = Student.find(params[:id])
        if student.update(student_params)
          redirect_to :action => "show", :id => student.id
        else
          redirect_to :action => "new"
        end
    end
    def destroy
        student = Student.find(params[:id])
        student.destroy
        redirect_to action: :index  
    end

    def one
        @students = Student.all
      end
    
      def two
        @students = Student.all
      end
    
      def three
        @students = Student.all
      end

        def four
          @students = Student.all
        end




    private
      def student_params
        params.require(:student).permit(:genre, :major, :grade, :title, :category, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>kwansei</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
   <h1>新入生・在校生向け</h1>
   <h1>関学文学部　質問サイト</h1>
   <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
   </div>
   </header>
   <main>
   <%= yield %>
   </main>
  </body>
</html>

app/views/students/edit.html.erb
<%= form_for @student do |f| %>
    <%= f.label :genre %>

    <%= f.text_field :genre, :size => 140 %> 
    <br>
    
    <br>
    # データ型がstringで選択式の入力フォーム
  <div class="field">
  <%= f.label :major  %>
  <%= f.select :major, 
  [["A", "A"], 
  ["B", "B"], 
  ["C", "C"]], include_blank: "選択して下さい" %>
</div>

# データ型がintegerで数字のみを入力するフォーム
<div class="field">
  <%= f.label :grade  %>
  <%= f.number_field :grade, :size => 10 %>
</div>

# データ型がtextで自由記述の入力フォーム
<div class="field">
  <%= f.label :title  %>
  <%= f.text_area :title, :size => "30x2" %>
</div>
    <%= f.submit "編集する" %>
<% end %>

app/views/students/four.html.erb
<h1>4年生</h1>
<% @students.each do |t| %>
  <% if t.grade == "4" %>  
  <div class="student">
   
  <%= image_tag t.image_url, size: "250x200" if t.image? %>

  <%= t.user.email %>
 
  

  <% if user_signed_in? %>
   <% if current_user.already_liked?(t) %>
       <%= button_to student_like_path(id: t.id, student_id: t.id), method: :delete do %>
           <p>いいねを取り消す</p><%= t.likes.count %>
       <% end %>
   <% else %>
       <%= button_to student_likes_path(id: t.id, student_id: t.id), method: :post do %>
           <p>いいね</p><%= t.likes.count %>
       <% end %>
   <% end %>
  <% else %>
   <p>いいねの数 = </p><%= t.likes.count %>
  <% end %>

  
   <%= t.grade %>
   <%= t.title %>

   
    
 
 
   
 
   <p class="time"><%= t.created_at %></p>


   <div class="right-container">
    <%= link_to "詳細へ", student_path(t.id) %>
    <% if user_signed_in? && current_user.id == t.user_id %>
    <%= link_to "編集する", edit_student_path(t.id) %>
    <%= button_to "削除する", student_path(t.id), method: :delete %>
  </div>
    <% end %>
</div>
  <% end %>
<% end %>
<%= link_to "一覧に戻る", students_path %>

app/views/students/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>
<div class="student">
 <h3>投稿を検索</h3>
 <h3><%= link_to "1年生", students_one_path %></h3>
 <h3><%= link_to "2年生", students_two_path %></h3>
 <h3><%= link_to "3年生", students_three_path %></h3>
 <h3><%= link_to "4年生", students_four_path %></h3>


 <h3><%= link_to "新規投稿へ", new_student_path %></h3>
</div>

<div class="student">

  <%= page_entries_info @students %>
  <%= paginate @students %>
  </div>

  <div class="students-container">
   <h3>一覧ページ</h3>
   <% @students.each do |t| %>

    <div class="student">
   
     <%= image_tag t.image_url, size: "250x200" if t.image? %>

     <%= t.user.email %>
    
     

     <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= button_to student_like_path(id: t.id, student_id: t.id), method: :delete do %>
              <p>いいねを取り消す</p><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= button_to student_likes_path(id: t.id, student_id: t.id), method: :post do %>
              <p>いいね</p><%= t.likes.count %>
          <% end %>
      <% end %>
     <% else %>
      <p>いいねの数 = </p><%= t.likes.count %>
     <% end %>

      <%= t.genre %>
      <%= t.major %>
      <%= t.grade %>
      <%= t.title %>

    
      <p class="time"><%= t.created_at %></p>
 

      <div class="right-container">
       <%= link_to "詳細へ", student_path(t.id) %>
       <% if user_signed_in? && current_user.id == t.user_id %>
         <%= link_to "編集する", edit_student_path(t.id) %>
       <%= button_to "削除する", student_path(t.id), method: :delete %>
     <% end %>
        </div>
    </div>
     <% end %>
    
  </div> 

app/views/students/new.html.erb
<h1>(関学文学部　質問サイト)</h1>
<h3>新規投稿ページ</h3>
<%= form_for @student do |f| %>

   
  <%= f.select :grade,
  [["1年生", "1"], 
  ["2年生", "2"],
  ["3年生", "3"],
  ["4年生", "4"]
  ], include_blank: "選択して下さい" %>




  <div class="field">
    <%= f.label :title  %>
    <%= f.text_area :title, :size => "30x2" %>
  </div>

  <div class="field">
  <%= f.label :qestion  %>
  <%= f.text_area :qestion, :size => "30x2" %>
</div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", students_path %>

app/views/students/one.html.erb
<h1>1年生</h1>
#詳細は後で追記,ネコとハダカデバネズミも同様
<% @students.each do |t| %>
    <% if t.grade == "1" %>  #ここがポイント！ categoryカラムにdogと格納されているものだけを表示している！
    <div class="student">
   
    <%= image_tag t.image_url, size: "250x200" if t.image? %>

    <%= t.user.email %>
   
    

    <% if user_signed_in? %>
     <% if current_user.already_liked?(t) %>
         <%= button_to student_like_path(id: t.id, student_id: t.id), method: :delete do %>
             <p>いいねを取り消す</p><%= t.likes.count %>
         <% end %>
     <% else %>
         <%= button_to student_likes_path(id: t.id, student_id: t.id), method: :post do %>
             <p>いいね</p><%= t.likes.count %>
         <% end %>
     <% end %>
    <% else %>
     <p>いいねの数 = </p><%= t.likes.count %>
    <% end %>

    
     <%= t.grade %>
     <%= t.title %>

     
      
   
   
     
   
     <p class="time"><%= t.created_at %></p>


     <div class="right-container">
      <%= link_to "詳細へ", student_path(t.id) %>
      <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_student_path(t.id) %>
      <%= button_to "削除する", student_path(t.id), method: :delete %>
    </div>
      <% end %>
   </div>
    <% end %>
    
  <% end %>
  <%= link_to "一覧に戻る", students_path %>

app/views/students/show.html.erb
<h1>background-color: #e0c9b5;</h1>
<h3>詳細</h3>
<div class="student">
  <%= @student.genre %>
  <%= @student.major %>
  <%= @student.grade %>
  <%= @student.title %>

 <%= @student.created_at %>
  <% if user_signed_in? %>
      <% if current_user.already_liked?(@student) %>
        <%= button_to student_like_path(@student), method: :delete do %>
          <p>いいねを取り消す</p><%= @student.likes.count %>
          <% end %>
         <% else %>   
          <%= button_to student_likes_path(@student), method: :post do %>
            <p>いいね</p><%= @student.likes.count %>
     <% end %>
       <% end %> 
    <% else %>
        <p>いいねの数 = </p><%= @student.likes.count %>
    <% end %>

 <%= link_to "編集する", edit_student_path(@student.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @student.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@student, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "一覧に戻る", students_path %>

app/views/students/three.html.erb
<h1>3年生</h1>
#詳細は後で追記,ネコとハダカデバネズミも同様
<% @students.each do |t| %>
  <% if t.grade == "3" %>  #ここがポイント！ categoryカラムにhadakadebanezumiと格納されているものだけを表示している！
  <div class="student">
   
  <%= image_tag t.image_url, size: "250x200" if t.image? %>

  <%= t.user.email %>
 
  

  <% if user_signed_in? %>
   <% if current_user.already_liked?(t) %>
       <%= button_to student_like_path(id: t.id, student_id: t.id), method: :delete do %>
           <p>いいねを取り消す</p><%= t.likes.count %>
       <% end %>
   <% else %>
       <%= button_to student_likes_path(id: t.id, student_id: t.id), method: :post do %>
           <p>いいね</p><%= t.likes.count %>
       <% end %>
   <% end %>
  <% else %>
   <p>いいねの数 = </p><%= t.likes.count %>
  <% end %>

   <%= t.genre %>
   <%= t.major %>
   <%= t.grade %>
   <%= t.title %>

   
    
 
 
   
 
   <p class="time"><%= t.created_at %></p>


   <div class="right-container">
    <%= link_to "詳細へ", student_path(t.id) %>
    <% if user_signed_in? && current_user.id == t.user_id %>
    <%= link_to "編集する", edit_student_path(t.id) %>
    <%= button_to "削除する", student_path(t.id), method: :delete %>
  </div>
    <% end %>
</div>
  <% end %>
<% end %>
<%= link_to "一覧に戻る", students_path %>

app/views/students/two.html.erb
<h1>2年生</h1>


<% @students.each do |t| %>
  <% if t.grade == "2" %>  #ここがポイント！ categoryカラムにcatと格納されているものだけを表示している！
  <div class="student">
   
  <%= image_tag t.image_url, size: "250x200" if t.image? %>

  <%= t.user.email %>
 
  

  <% if user_signed_in? %>
   <% if current_user.already_liked?(t) %>
       <%= button_to student_like_path(id: t.id, student_id: t.id), method: :delete do %>
           <p>いいねを取り消す</p><%= t.likes.count %>
       <% end %>
   <% else %>
       <%= button_to student_likes_path(id: t.id, student_id: t.id), method: :post do %>
           <p>いいね</p><%= t.likes.count %>
       <% end %>
   <% end %>
  <% else %>
   <p>いいねの数 = </p><%= t.likes.count %>
  <% end %>

   <%= t.genre %>
   <%= t.major %>
   <%= t.grade %>
   <%= t.title %>

   
    
 
 
   
 
   <p class="time"><%= t.created_at %></p>


   <div class="right-container">
    <%= link_to "詳細へ", student_path(t.id) %>
    <% if user_signed_in? && current_user.id == t.user_id %>
    <%= link_to "編集する", edit_student_path(t.id) %>
    <%= button_to "削除する", student_path(t.id), method: :delete %>
  </div>
    <% end %>
</div>
  <% end %>
<% end %> 
 <%= link_to "一覧に戻る", students_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>